### ISSUE TITLE
TypeError: Cannot read property 'setValue' of undefined

### ISSUE THREAD

**Issue by MrRob** [KyleJonesWinsted/suitecloud-unit-testing-stubs#1]
Hey Kyle!

I'm getting an error when I try using your new mocking format with the example suitelet from the Oracle module.  I'm attaching a screenshot here to show you what I mean.  Have I done something wrong?

Thank you!

Robbie

<img width="1591" alt="Screenshot 2021-11-08 at 15 53 01" src="https://user-images.githubusercontent.com/448678/140774496-02a92b97-e5ba-4cc9-8fab-92b4dc1f19ae.png">

**Comment by KyleJonesWinsted** [comment]
Hi Rob,

I believe the issue here is you haven't told Jest what to return for `record.load`. If you add your mock record `rec` as a return value for `record.load` this error should go away. Add this on line 22 of your test:

```js
 record.load.mockReturnValue(rec);
```

This is different than the way Netsuite's original stubs work. My way allows you to mock different return values for different records. With the Netsuite stubs, every record shares the same mock return values.

**Comment by MrRob** [comment]
You are correct, that fixed it, thank you!
